name: Unzip Images

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip images
        run: |
          cd image
          unzip NM.zip
          rm NM.zip
          
      - name: Commit changes
        run: |
          git config --local superjohnson1984@gmail.com "github-actions[bot]@users.noreply.github.com"
          git config --local supercrypto1984 "github-actions[bot]"
          git add image/
          git commit -m "Extract images from NM.zip" || echo "No changes to commit"
          git push

